apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cxi-dra-driver
  namespace: kube-system
  labels:
    app: cxi-dra-driver
spec:
  selector:
    matchLabels:
      app: cxi-dra-driver
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cxi-dra-driver
    spec:
      serviceAccountName: cxi-dra-driver
      hostPID: true
      priorityClassName: system-node-critical
      containers:
        - name: driver
          image: __IMAGE__
          imagePullPolicy: Never
          command:
            - /cxi-dra-driver
          args:
            - --driver-name=cxi.slingshot.hpe.com
            - --cdi-root=/var/run/cdi
            - --plugin-dir=/var/lib/kubelet/plugins/cxi.slingshot.hpe.com
            - --registrar-dir=/var/lib/kubelet/plugins_registry
            - --mock-devices=__MOCK_DEVICES__
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: dev
              mountPath: /dev
            - name: kubelet-plugins
              mountPath: /var/lib/kubelet/plugins/cxi.slingshot.hpe.com
            - name: kubelet-registry
              mountPath: /var/lib/kubelet/plugins_registry
            - name: cdi
              mountPath: /var/run/cdi
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: dev
          hostPath:
            path: /dev
        - name: kubelet-plugins
          hostPath:
            path: /var/lib/kubelet/plugins/cxi.slingshot.hpe.com
            type: DirectoryOrCreate
        - name: kubelet-registry
          hostPath:
            path: /var/lib/kubelet/plugins_registry
        - name: cdi
          hostPath:
            path: /var/run/cdi
            type: DirectoryOrCreate
